version: '3.8'

services:
  api:
    build: .
    container_name: incident_classifier_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6.0
    container_name: incident_classifier_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.0
    container_name: incident_classifier_redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
